### ISSUE TITLE
Median is not correctly calculated

### ISSUE THREAD

**Issue by dsoprea** [commonsmachinery/blockhash-js#14]
Same as in https://github.com/commonsmachinery/blockhash/pull/23 in the C implementation and https://github.com/commonsmachinery/blockhash-python/pull/9 in the Python implementation. Likely contributes to issue https://github.com/commonsmachinery/blockhash-js/issues/7 since this causes all hashes to be incorrect.

https://github.com/commonsmachinery/blockhash-js/blob/ef9e1ed4f7521d515dc1ce5cecd6da19290ed583/index.js#L28

**Comment by artfwo** [comment]
@dsoprea Thanks for reporting this here too :) Does the linked PR fix the problem?

**Comment by dsoprea** [comment]
Seems like it should, but I'm unable to test simply using Node.

1. Your package.json uses "devDependencies" instead of "dependencies", so the dependencies won't automatically install unless you pass "--dev" to npm-install.
2. When I adjusted this so that I could get the dependencies installed, I got an error 

```
> b = require('blockhash')
{ hammingDistance: [Function: hammingDistance],
  blockhash: [Function: blockhash],
  blockhashData: [Function: blockhashData] }
> b.blockhash('test_assets/20170618_155330.jpg')
ReferenceError: XMLHttpRequest is not defined
    at Object.blockhash (/home/local/MAGICLEAP/doprea/development/node/testproject/node_modules/blockhash/index.js:217:15)
    at repl:1:3
    at sigintHandlersWrap (vm.js:22:35)
...
```

It seems like this project is singularly meant for use in webpages and not via Node. I'd remove any references to Node/NPM (including package.json; you'll have to make sure that all dependencies are represented properly in the webpage example) from the documentation while these issues exist, if indeed it was ever your intent for this to work in NPM, in order to mitigate confusion.

**Comment by dsoprea** [comment]
By the way, I could use some insight from you. 

I had quickly translated the algorithm to Go based on your Python and C implementations (which is how I had noticed the median discrepancy). There is a subtle image-processing difference that might mean that all hashes produced using the standard Go image package will always differ from your hashes. 

Send me an email, if you have a chance, to discuss.

**Comment by artfwo** [comment]
Right, the library is mostly for browsers, but it also works with node (one use case for that is running the tests outside of a browser). I am currently able to run the tests locally using:
```
npm install
npm install mocha (or add --dev to the above command)
./node_modules/mocha/bin/mocha
```
This should be probably documented. Mocha provides XMLHttpRequest, Date and other browser-specific stuff in the global namespace. The hashes currently match those from blockhash-python test data, so if you have no objections, I'd merge this change immediately. I'll send a follow-up email regarding your image processing differences ASAP.
